---
name: Test Coverage

permissions: {}

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/codecov.yml
      - src/**/*.rs
      - tests/**/*.rs
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/codecov.yml
      - src/**/*.rs
      - tests/**/*.rs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: taiki-e/install-action@5f57d6cb7cd20b14a8a27f522884c4bc8a187458 # v2.75.19
        with:
          tool: cargo-tarpaulin
      - name: Run instrumented tests
        run: cargo tarpaulin --all-targets --skip-clean --out xml
        env:
          RUST_LOG: cargo_tarpaulin=error
      - name: Upload codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
